export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST";
export const FETCH_BOOKS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_BOOKS_FAILURE = "FETCH_USERS_FAILUTE";
export const FETCH_BOOK_BY_ID_SUCCESS = "FETCH_BOOK_BY_ID_SUCCESS";
export const FETCH_BOOK_BY_ID_FAILURE = "FETCH_BOOK_BY_ID_FAILURE";
